### ISSUE TITLE
doc: add serial number column in the component table

### ISSUE THREAD

**Issue by chankruze** [geekofia/tailwind-ui-components#5]
It will be better to have a count on how many components we are currently keeping track of. Hence there should be a `S.No.` column in the README.

**Task**
- [ ] Add `S.No.` column to the [Components](https://github.com/geekofia/tailwind-ui-components#components)

**Expected Result**
![image](https://user-images.githubusercontent.com/29806845/194915903-06a62b3e-4266-41b3-91f0-428c6714bba6.png)

**Comment by FixxooXD** [comment]
Yup sure 👍
